# Generated by Django 3.2.6 on 2021-08-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
                ('image', models.ImageField(default='product.png', upload_to='books/', verbose_name='تصویر')),
                ('author', models.CharField(max_length=50, verbose_name='نویسنده')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='قیمت به تومان')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('stock', models.IntegerField(default=1, verbose_name='موجودی')),
                ('description', models.CharField(default='بدون توضیحات', max_length=500, verbose_name='درباره کتاب')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ManyToManyField(to='book.Category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
                'ordering': ('-price',),
            },
        ),
    ]
