# Generated by Django 3.2.6 on 2021-08-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashcoupon',
            options={'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیف درصدی سبدخرید'},
        ),
        migrations.RenameField(
            model_name='cashcoupon',
            old_name='discount',
            new_name='discount_percent',
        ),
    ]
