# Generated by Django 3.2.6 on 2021-08-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20210814_1740'),
        ('coupon', '0002_auto_20210820_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashCoupon',
            new_name='CartCoupon',
        ),
    ]
