# Generated by Django 3.2.6 on 2021-08-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_rename_cashcoupon_cartcoupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCashCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'تخفیف نقدی کتاب',
                'verbose_name_plural': 'تخفیف نقدی کتاب ها',
            },
        ),
        migrations.AlterModelOptions(
            name='cartcoupon',
            options={'verbose_name': 'تخفیف درصدی سبد', 'verbose_name_plural': 'تخفیف درصدی سبدهای خریده'},
        ),
    ]
