# Generated by Django 3.2.6 on 2021-08-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_book_discount'),
        ('coupon', '0004_auto_20210821_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcashcoupon',
            name='books',
            field=models.ManyToManyField(blank=True, to='book.Book'),
        ),
    ]
