# Generated by Django 3.2.6 on 2021-08-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_book_discount'),
        ('coupon', '0005_bookcashcoupon_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPercentCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('discount_percent', models.IntegerField(default=0)),
                ('books', models.ManyToManyField(blank=True, to='book.Book')),
            ],
            options={
                'verbose_name': 'تخفیف درصدی کتاب',
                'verbose_name_plural': 'تخفیف درصدی کتاب ها',
            },
        ),
    ]
