# Generated by Django 3.2.6 on 2021-08-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210823_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='national_code',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
