# Generated by Django 3.2.6 on 2021-08-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_anonymous_user',
            field=models.BooleanField(default=False, verbose_name='کاربرناشناس'),
        ),
    ]
