# Generated by Django 3.2.6 on 2021-08-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartcoupon',
            options={'verbose_name': 'تخفیف درصدی سبد', 'verbose_name_plural': 'تخفیف درصدی سبدهای خرید'},
        ),
        migrations.AlterField(
            model_name='bookcashcoupon',
            name='books',
            field=models.ManyToManyField(blank=True, to='book.Book', verbose_name='کتاب ها'),
        ),
        migrations.AlterField(
            model_name='bookcashcoupon',
            name='discount_price',
            field=models.IntegerField(default=0, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='bookcashcoupon',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='bookcashcoupon',
            name='valid_from',
            field=models.DateTimeField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='bookcashcoupon',
            name='valid_to',
            field=models.DateTimeField(verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='bookpercentcoupon',
            name='books',
            field=models.ManyToManyField(blank=True, to='book.Book', verbose_name='کتاب ها'),
        ),
        migrations.AlterField(
            model_name='bookpercentcoupon',
            name='discount_percent',
            field=models.IntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='bookpercentcoupon',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='bookpercentcoupon',
            name='valid_from',
            field=models.DateTimeField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='bookpercentcoupon',
            name='valid_to',
            field=models.DateTimeField(verbose_name='تاریخ انقضا'),
        ),
        migrations.AlterField(
            model_name='cartcoupon',
            name='code',
            field=models.CharField(max_length=30, verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='cartcoupon',
            name='discount_percent',
            field=models.IntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='cartcoupon',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='cartcoupon',
            name='valid_from',
            field=models.DateTimeField(verbose_name='تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='cartcoupon',
            name='valid_to',
            field=models.DateTimeField(verbose_name='تاریخ انقضا'),
        ),
    ]
