# Generated by Django 3.2.6 on 2021-08-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20210814_1740'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartitems'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AddField(
            model_name='cart',
            name='finalized_orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.finalizedorders'),
        ),
    ]
