# Generated by Django 3.2.6 on 2021-08-18 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210815_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='finalized_orders',
        ),
        migrations.AddField(
            model_name='finalizedorders',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
