# Generated by Django 3.2.6 on 2021-08-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cart', '0005_auto_20210818_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalizedorders',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.shippingaddress'),
        ),
        migrations.AlterField(
            model_name='finalizedorders',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
