# Generated by Django 3.2.6 on 2021-08-18 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20210818_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalizedorders',
            options={'verbose_name': 'فاکتورخرید', 'verbose_name_plural': 'فاکتورهای خرید'},
        ),
        migrations.AddField(
            model_name='finalizedorders',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartitems'),
        ),
    ]
