# Generated by Django 3.2.6 on 2021-08-18 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20210818_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizedorders',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartitems'),
        ),
    ]
