# Generated by Django 3.2.6 on 2021-08-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_finalizedorders_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalizedorders',
            name='item',
        ),
        migrations.AddField(
            model_name='finalizedorders',
            name='item',
            field=models.ManyToManyField(to='cart.CartItems'),
        ),
    ]
