# Generated by Django 3.2.6 on 2021-08-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20210818_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='ordered',
            field=models.CharField(choices=[('F', 'finalized'), ('U', 'unordered'), ('O', 'ordering')], default='U', max_length=4),
        ),
    ]
