# Generated by Django 3.2.6 on 2021-08-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cartitems_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalizedorders',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
