# Generated by Django 3.2.6 on 2021-08-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_rename_cashcoupon_cartcoupon'),
        ('cart', '0011_finalizedorders_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizedorders',
            name='discount',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='coupon.cartcoupon'),
        ),
    ]
