# Generated by Django 3.2.6 on 2021-08-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_alter_finalizedorders_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalizedorders',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
