# Generated by Django 3.2.6 on 2021-08-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_alter_finalizedorders_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizedorders',
            name='discount',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
