# Generated by Django 3.2.6 on 2021-08-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_finalizedorders_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalizedorders',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
