# Generated by Django 3.2.6 on 2021-08-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
