# Generated by Django 3.2.6 on 2021-08-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210813_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-price',)},
        ),
    ]
