# Generated by Django 3.2.6 on 2021-08-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='بدون توضیحات', max_length=500),
        ),
    ]
