# Generated by Django 3.2.6 on 2021-08-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-price',), 'verbose_name': 'کتاب', 'verbose_name_plural': 'کتاب ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
