# Generated by Django 3.2.6 on 2021-08-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('book', '0007_book_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount',
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.ManyToManyField(blank=True, to='coupon.CashCoupon'),
        ),
    ]
