# Generated by Django 3.2.6 on 2021-08-31 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_is_anonymous_user'),
        ('book', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد سبد'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی سبد'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='کتاب'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='سبد'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='ordered',
            field=models.CharField(choices=[('F', 'پرداخت و تمام شده'), ('U', 'موجود در لیست خرید بعدی'), ('O', 'موجود در سبد خرید')], default='U', max_length=4, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='finalizedorders',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='سبد'),
        ),
        migrations.AlterField(
            model_name='finalizedorders',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد فاکتور'),
        ),
        migrations.AlterField(
            model_name='finalizedorders',
            name='discount',
            field=models.IntegerField(default='0', verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='finalizedorders',
            name='item',
            field=models.ManyToManyField(to='cart.CartItems', verbose_name='سفارشات'),
        ),
        migrations.AlterField(
            model_name='finalizedorders',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='finalizedorders',
            name='price',
            field=models.IntegerField(default=0, verbose_name='هزینه'),
        ),
        migrations.AlterField(
            model_name='finalizedorders',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.shippingaddress', verbose_name='ادرس تحویل'),
        ),
    ]
