# Generated by Django 3.2.6 on 2021-08-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=300)),
                ('default_address', models.BooleanField(default=False)),
            ],
        ),
    ]
