# Generated by Django 3.2.6 on 2021-08-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_shippingaddress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='user',
            field=models.IntegerField(default=2, max_length=5),
        ),
    ]
